### PR TITLE
640: making json file readable with comments.

### LINKED ISSUE #640: Error activating extension while trying to read json file with comments
**Describe the bug**
The error below happens when I activate the extension:

2025-01-08 16:31:53.270 [info] ExtensionService#_doActivateExtension BalticAmadeus.pro-bro, startup: false, activationEvent: 'onView:pro-bro-databases'
2025-01-08 16:31:53.424 [error] Activating extension BalticAmadeus.pro-bro failed due to an error:
2025-01-08 16:31:53.424 [error] SyntaxError: Expected double-quoted property name in JSON at position 36 (line 2 column 34)
    at JSON.parse (<anonymous>)
    at wt (c:\Users\ronil\.vscode\extensions\balticamadeus.pro-bro-1.8.0\out\extension.js:94:839)
    at y (c:\Users\ronil\.vscode\extensions\balticamadeus.pro-bro-1.8.0\out\extension.js:110:1975)
    at c:\Users\ronil\.vscode\extensions\balticamadeus.pro-bro-1.8.0\out\extension.js:110:1845
    at Qt (c:\Users\ronil\.vscode\extensions\balticamadeus.pro-bro-1.8.0\out\extension.js:110:1773)
    at K0.n (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4447)
    at K0.m (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4410)
    at K0.l (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:3866)

I'm running vscode version 1.96.2 on Windows 11, version 24h2
ProBro Version: 1.8.0

My openedge-project.json:
{
    "name": "Unificacao de bases", // Project name, will be used in the future for dependency management
    "version": "1.0",    // Project version number, will be used in the future for dependency management
    "oeversion": "12.2", // Must reference an existing ABL version in Settings -> Extensions -> ABL Configuration -> Runtimes
    "graphicalMode": false, // True for prowin[32], false for _progres
    "charset": "iso8859-1",
    "extraParameters": "-basekey INI -ininame C:/Totvs/datasul/vscode/scripts/datasul.ini -pf C:/Totvs/datasul/vscode/scripts/datasul.pf", // Extra Progress command line parameters
    "preprocessor": { // Customize parser behavior (optional)
      // "windowSystem": "MS-WINDOWS",
      // "processArchitecture": 32
    },
    // Only required if your project use extensions other than ".i" for include files.
    // If not specified, modifying files with such extension will not trigger a compilation
    "includeFileExtensions": [ ".i", ".f" ],
    "buildPath": [
      // Entries can have type 'source' or 'propath'. Path attribute is mandatory. Build attribute is optional (defaults to 'path'). Xref attribute is optional (defaults to 'build/.pct' or '.builder/srcX')      
      { "type": "source", "path": "newell/unificacao"},
      { "type": "source", "path": "newell/unificacao/aftersales"},
      { "type": "source", "path": "newell/espJCS"},
      { "type": "source", "path": "newell/espNBB"},
      { "type": "source", "path": "C:/Totvs/datasul/vscode/apoio/foundation"},
      { "type": "source", "path": "C:/Totvs/datasul/vscode/apoio/ems2"},
      { "type": "source", "path": "C:/Totvs/datasul/vscode/apoio/ems5"},
      { "type": "source", "path": "C:/Totvs/datasul/vscode/apoio/ddk"},
      { "type": "propath", "path": "C:/Progress/OpenEdge/tty/netlib/OpenEdge.net.pl"}
    ],
    "dbConnections": [ // Unlimited number of connections - Beware of -h
      {
        "name": "ems2cad", // Logical name of database, or physical name if -ld is not used
        "connect": "-db ems2cad -H srvtotvs12 -S 23611 -U sysprogress -P aaa-ld mgcad", // ABL connection string
        "schemaFile": "dump/ems2cad.df",
        "aliases": []
      },
      {
        "name": "ems2mov", // Logical name of database, or physical name if -ld is not used
        "connect": "-db ems2mov -H srvtotvs12 -S 23601 -U sysprogress -P aaa-ld mgmov", // ABL connection string
        "schemaFile": "dump/ems2mov.df",
        "aliases": []
      },
      {
        "name": "ems5cad", // Logical name of database, or physical name if -ld is not used
        "connect": "-db ems5cad -H srvtotvs12 -S 23605 -U sysprogress -P aaa-ld emscad", // ABL connection string
        "schemaFile": "dump/ems5cad.df",
        "aliases": []
      },
      {
        "name": "ems5mov", // Logical name of database, or physical name if -ld is not used
        "connect": "-db ems5mov -H srvtotvs12 -S 23606 -U sysprogress -P aaa-ld emsmov", // ABL connection string
        "schemaFile": "dump/ems5mov.df",
        "aliases": []
      },
      {
        "name": "emsfnd", // Logical name of database, or physical name if -ld is not used
        "connect": "-db emsfnd  -H srvtotvs12 -S 23619 -U sysprogress -P aaa-ld emsfnd", // ABL connection string
        "schemaFile": "dump/emsfnd.df",
        "aliases": []
      },
      {
        "name": "hcm", // Logical name of database, or physical name if -ld is not used
        "connect": "-db hcm  -H srvtotvs12 -S 23607 -U sysprogress -P aaa-ld hcm", // ABL connection string
        "schemaFile": "dump/hcm.df",
        "aliases": []
      },
      {
        "name": "ems2esp-jcs", // Logical name of database, or physical name if -ld is not used
        "connect": "-db ems2esp-jcs -H srvtotvs12 -S 50049 -ld emsesp", // ABL connection string
        "schemaFile": "dump/ems2esp-jcs.df", //dump/ems2esplilo.df
        "aliases": []
      }
      
    ],
    "numThreads": 1, // Number of OpenEdge sessions handling build
    "procedures": [
      // List of procedures executed before the main entry point
      // Init mode -> before setting propath and DB connections
      // Once, persistent and super -> after setting propath and DB connections
      //{ "name": "scripts/login.p", "mode": "once" /* Mode can be init, once, persistent or super */ }
      {"name": "C:/Totvs/datasul/vscode/scripts/datasul-desenv.p", "mode": "persistent"}

    ],
    "profiles": [ /* See section below */ ]
  }

### PR DESCRIPTION
**Pull request by SeNaSa231**

### CODE REVIEW

File: src/common/OpenEdgeJsonReaded.ts [hunk 1]
```diff
@@ -2,21 +2,22 @@ import { PfParser } from '../view/app/utils/PfParser';
 import { IConfig } from '../view/app/model';
 import * as path from 'path';
 import * as fs from 'fs';
+import jsonminify = require('jsonminify');
```
Comment (PauliusKu) [inline src/common/OpenEdgeJsonReaded.ts:5]: why do we use require here instead of import ... from ... ?
